[package]
name = "quadtree"
version = "0.1.0"
authors = ["_Bare <bare@logixsr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.15.1"
rand = "0.7.3"
rand_distr = "0.2.2"
num-traits = "0.2.12"
